server:
  port: 1011

spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/bank?currentSchema=account
    username: yandex
    password: yandex
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: account
  thymeleaf:
    encoding: UTF-8
  liquibase:
    change-log: classpath:/db/changelog/rootChangeLog.xml
    liquibase-schema: public
    default-schema: account
    parameters:
      schemaName: account
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/bank?currentSchema=account
    user: yandex
    password: yandex
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/bankapp
        registration:
          bankapp:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: bankapp
            client-secret: pZKtfdB6CVeUwHGuUPnvEgXsL8R71iHX
            scope:
              - profile
            client-authentication-method: client_secret_post
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    liquibase:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.web: DEBUG
    org.company.account: DEBUG
    liquibase: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/