server:
  port: 1014

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account
              uri: lb://account
              predicates:
                - Path=/account/**
              filters:
                - StripPrefix=1
            - id: transfer
              uri: lb://transfer
              predicates:
                - Path=/transfer/**
              filters:
                - StripPrefix=1
            - id: exchange
              uri: lb://exchange
              predicates:
                - Path=/exchange/**
              filters:
                - StripPrefix=1
            - id: cash
              uri: lb://cash
              predicates:
                - Path=/cash/**
              filters:
                - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/