server:
  port: 1014

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account
              uri: lb://account
              predicates:
                - Path=/account/**
              filters:
                - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/