server:
  port: 1018

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank?currentSchema=notification
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: notification
  thymeleaf:
    encoding: UTF-8
  liquibase:
    change-log: classpath:/db/changelog/rootChangeLog.xml
    liquibase-schema: public
    default-schema: notification
    parameters:
      schemaName: notification
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank?currentSchema=notification
    user: postgres
    password: postgres
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/bankapp
        registration:
          bankapp:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: bankapp
            client-secret: Xih8xBTW8WuoJvBRFzuhQ8DXbxdONfec
            scope:
              - profile
            client-authentication-method: client_secret_post
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    liquibase:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.web: DEBUG
    org.company.account: DEBUG
    liquibase: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/